name: App

on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: App running base job
    steps:
      - uses: actions/checkout@v3
      - id: base
        uses: ./.github/template/base
        with:
          version: '0.0.1'
          namespace: 'helloworld'
  checkit:
    environment: dev
    runs-on: ubuntu-latest
    name: App running base job
    steps:
      - uses: actions/checkout@v3
      - id: sample
        run: echo "${{ vars.ARM_SUBSCRIPTION_ID || secrets.ARM_SUBSCRIPTION_ID }}"
        shell: pwsh