name: frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/frontend**
    - frontend/**
  push:
    branches:
    - main
    paths:
    - .github/workflows/frontend**
    - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GitHubToken: ${{secrets.GITHUB_TOKEN}}
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      run: ./build.ps1
      shell: pwsh
      working-directory: frontend
