name: Sample

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      run: |
        curl \
        --request POST "https://api.humanitec.io/orgs/ikuto/artefact-versions" \
        --header "Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}" \
        --header "Content-Type: application/json" \
        --data-raw '{ \
            "name": "Sample", \
            "version": "latest", \
            "type": "container", \
            "commit": "${{ github.event.pull_request.head.sha }}", \
            "ref": "${{ github.event.pull_request.head.sha }}" \
        }'
